"""
scripts/check_rain_source.py

Compares NASA POWER rain with NASA GPM IMERG V07 Final Run daily rain for the five
district points and writes docs/results/rain_source_check.md:
  - yearly and Jun-Sep totals, POWER vs IMERG;
  - 2001-2014 vs 2016-2025 means;
  - Pettitt change-point test on each series (src/compute/change_point.py);
  - daily correlation POWER vs IMERG;
  - whether Feni and Noakhali differ in IMERG (they share one POWER cell).

Decision rule (fixed before the results were seen): IMERG "has a step change" if
the Pettitt p < 0.05 for the annual or the Jun-Sep totals of any district. Only if it
does not is IMERG made the default rain source.

Run from the repo root:
    python scripts/check_rain_source.py
"""

import os
import sys

import numpy as np
import pandas as pd
from scipy import stats

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
sys.path.insert(0, os.path.join(ROOT, "src", "compute"))
from change_point import pettitt_test  # noqa: E402
from weather import load_weather, RAIN_CITATIONS  # noqa: E402

OUT_PATH = os.path.join(ROOT, "docs", "results", "rain_source_check.md")
CELLS_PATH = os.path.join(ROOT, "data", "processed", "imerg_cells.csv")
DISTRICTS = ["cumilla", "feni", "noakhali", "brahmanbaria", "sylhet"]
ALPHA = 0.05
EARLY = (2001, 2014)
LATE = (2016, 2025)


def load_both(name):
    imerg = load_weather(name, rain_source="imerg")["rainfall_mm"]
    power = load_weather(name, rain_source="power")["rainfall_mm"]
    power = power.loc[imerg.index.min():imerg.index.max()]
    return power, imerg


def totals(rain):
    """Annual totals (complete years only) and Jun-Sep totals (complete seasons only)."""
    per_year_days = rain.groupby(rain.index.year).size()
    full_years = per_year_days[per_year_days >= 365].index
    annual = rain.groupby(rain.index.year).sum().loc[full_years]
    jjas_rain = rain[rain.index.month.isin([6, 7, 8, 9])]
    jjas_days = jjas_rain.groupby(jjas_rain.index.year).size()
    jjas = jjas_rain.groupby(jjas_rain.index.year).sum().loc[jjas_days[jjas_days == 122].index]
    return annual, jjas


def period_mean(series, period):
    s = series.loc[period[0]:period[1]]
    return s.mean(), s.index.min(), s.index.max()


def fmt_p(p):
    return "p<0.001" if p < 0.001 else f"p={p:.3f}"


def pettitt_cell(series):
    r = pettitt_test(series.values)
    year = series.index[r["split"]]
    text = (f"{year}, {fmt_p(r['p'])}, {r['mean_before']:.0f} -> {r['mean_after']:.0f} mm")
    return (f"**{text}**" if r["p"] < ALPHA else text), r["p"]


def lag_corr(a, b, lag):
    return a.corr(b.shift(lag))


def main():
    power, imerg, annual, jjas = {}, {}, {}, {}
    for name in DISTRICTS:
        power[name], imerg[name] = load_both(name)
        annual[name] = {"POWER": totals(power[name])[0], "IMERG": totals(imerg[name])[0]}
        jjas[name] = {"POWER": totals(power[name])[1], "IMERG": totals(imerg[name])[1]}
    cells = pd.read_csv(CELLS_PATH, index_col="district")
    first, last = imerg["feni"].index.min().date(), imerg["feni"].index.max().date()

    lines = []
    add = lines.append
    add("# Rain source check: NASA POWER vs NASA GPM IMERG (Task 5d)")
    add("")
    add("Generated by `scripts/check_rain_source.py`. Do not edit by hand; re-run the script.")
    add("")
    add(f"Daily rain for the five district points, {first} to {last} (the last day of IMERG "
        "V07 Final Run daily at GES DISC when this was run). All numbers are for NASA data "
        "for the area around each district point, not for a particular field.")
    add("")
    add("- **POWER**: NASA POWER daily, AG community, `PRECTOTCORR` (about 0.5 degree cell); "
        "Feni and Noakhali fall in the same POWER cell.")
    add("- **IMERG**: NASA GPM IMERG V07 Final Run daily, `GPM_3IMERGDF.07` "
        "(doi:10.5067/GPM/IMERGDF/DAY/07), 0.1 degree cell containing each point, "
        "downloaded with `scripts/fetch_imerg.py` through the NASA Giovanni time-series API.")
    add("")
    add("| District | point (lat, lon) | IMERG cell centre (lat, lon) |")
    add("|---|---|---|")
    for name in DISTRICTS:
        c = cells.loc[name]
        add(f"| {name.title()} | {c.point_lat:.4f}, {c.point_lon:.4f} | {c.cell_lat:.2f}, {c.cell_lon:.2f} |")
    add("")

    # --- Pettitt and decision -------------------------------------------------------
    pett = {}
    for name in DISTRICTS:
        for src in ("POWER", "IMERG"):
            for label, table in (("annual", annual), ("Jun-Sep", jjas)):
                pett[(name, src, label)] = pettitt_cell(table[name][src])
    imerg_breaks = [(n, lab) for (n, s, lab), (_, p) in pett.items() if s == "IMERG" and p < ALPHA]
    power_breaks = [(n, lab) for (n, s, lab), (_, p) in pett.items() if s == "POWER" and p < ALPHA]

    add("## Decision")
    add("")
    add("Rule, fixed before the results were seen: IMERG has a step change if the Pettitt "
        f"test gives p < {ALPHA} for the annual or the Jun-Sep totals of any district.")
    add("")
    if imerg_breaks:
        listed = "; ".join(f"{n.title()} {lab}" for n, lab in imerg_breaks)
        add(f"- **IMERG also shows a significant change point** ({listed}). IMERG is **not** "
            "switched on as the default rain source; see the tables below.")
    else:
        add("- **IMERG shows no significant change point** in any district, annual or Jun-Sep. "
            "IMERG is the default rain source (`load_weather(district)` in "
            "`src/compute/weather.py`) for the water balance, the hindcast and everything "
            "downstream.")
    add(f"- POWER: {len(power_breaks)} of {2 * len(DISTRICTS)} series have p < {ALPHA} "
        "(" + ("; ".join(f"{n.title()} {lab}" for n, lab in power_breaks) or "none") + ").")
    add("")

    add("## Pettitt change-point test")
    add("")
    add("Each cell: first year after the change point, p, mean before -> mean after (mm). "
        f"**Bold** = p < {ALPHA}. Annual: complete years "
        f"{annual['feni']['IMERG'].index.min()}-{annual['feni']['IMERG'].index.max()}; "
        f"Jun-Sep: {jjas['feni']['IMERG'].index.min()}-{jjas['feni']['IMERG'].index.max()}. "
        "Pettitt (1979), approximate p. A steady trend can also give a small p, so read the "
        "means before and after too.")
    add("")
    add("| District | POWER annual | IMERG annual | POWER Jun-Sep | IMERG Jun-Sep |")
    add("|---|---|---|---|---|")
    for name in DISTRICTS:
        add(f"| {name.title()} | {pett[(name, 'POWER', 'annual')][0]} | {pett[(name, 'IMERG', 'annual')][0]} "
            f"| {pett[(name, 'POWER', 'Jun-Sep')][0]} | {pett[(name, 'IMERG', 'Jun-Sep')][0]} |")
    add("")
    add("**POWER / IMERG ratio of annual totals** (a relative check: with IMERG as the reference, "
        "a break here is a jump in POWER alone):")
    add("")
    add("| District | Pettitt on POWER/IMERG annual ratio | ratio 2001-2014 | ratio 2016-2024 |")
    add("|---|---|---|---|")
    for name in DISTRICTS:
        ratio = annual[name]["POWER"] / annual[name]["IMERG"]
        r = pettitt_test(ratio.values)
        cell = (f"{ratio.index[r['split']]}, {fmt_p(r['p'])}, {r['mean_before']:.2f} -> "
                f"{r['mean_after']:.2f}")
        cell = f"**{cell}**" if r["p"] < ALPHA else cell
        add(f"| {name.title()} | {cell} | {ratio.loc[2001:2014].mean():.2f} | {ratio.loc[2016:2024].mean():.2f} |")
    add("")

    # --- 2001-2014 vs 2016-2025 -----------------------------------------------------
    add(f"## Mean {EARLY[0]}-{EARLY[1]} vs {LATE[0]}-{LATE[1]}")
    add("")
    add("2015 is left out as the transition year. Annual totals run to 2024 (2025 is not "
        "complete in IMERG); Jun-Sep to 2025. Change = later mean / earlier mean - 1.")
    add("")
    add("| District | POWER annual early / late (mm) | change | IMERG annual early / late (mm) | change "
        "| POWER Jun-Sep early / late (mm) | change | IMERG Jun-Sep early / late (mm) | change |")
    add("|---|---|---|---|---|---|---|---|---|")
    for name in DISTRICTS:
        cells_row = []
        for table in (annual, jjas):
            for src in ("POWER", "IMERG"):
                e, _, _ = period_mean(table[name][src], EARLY)
                l, _, _ = period_mean(table[name][src], LATE)
                cells_row += [f"{e:.0f} / {l:.0f}", f"{(l / e - 1) * 100:+.0f}%"]
        add(f"| {name.title()} | " + " | ".join(cells_row) + " |")
    add("")

    # --- Daily correlation ----------------------------------------------------------
    add("## Daily correlation, POWER vs IMERG")
    add("")
    add("Pearson r of daily rain. Lag: IMERG shifted by one day (IMERG days are UTC days); "
        "the best lag shows whether the two daily records line up.")
    add("")
    add("| District | r, all days | r, 2001-2014 | r, 2016-2025 | r, IMERG one day earlier | r, IMERG one day later | r, monthly totals |")
    add("|---|---|---|---|---|---|---|")
    for name in DISTRICTS:
        p, i = power[name], imerg[name]
        monthly_p = p.resample("MS").sum()
        monthly_i = i.resample("MS").sum()
        add(f"| {name.title()} | {p.corr(i):.2f} | {p.loc['2001':'2014'].corr(i.loc['2001':'2014']):.2f} "
            f"| {p.loc['2016':'2025'].corr(i.loc['2016':'2025']):.2f} | {lag_corr(p, i, 1):.2f} "
            f"| {lag_corr(p, i, -1):.2f} | {monthly_p.corr(monthly_i):.2f} |")
    add("")

    # --- Feni vs Noakhali -----------------------------------------------------------
    f_i, n_i = imerg["feni"], imerg["noakhali"]
    f_p, n_p = power["feni"], power["noakhali"]
    ann_f, ann_n = annual["feni"]["IMERG"], annual["noakhali"]["IMERG"]
    jj_f, jj_n = jjas["feni"]["IMERG"], jjas["noakhali"]["IMERG"]
    w_ann = stats.wilcoxon(ann_f, ann_n)
    w_jj = stats.wilcoxon(jj_f, jj_n)
    same_days = float((f_i.round(2) == n_i.round(2)).mean())
    add("## Do Feni and Noakhali now differ?")
    add("")
    add(f"- POWER: identical rain on {(f_p == n_p).mean() * 100:.0f}% of days (one shared cell).")
    add(f"- IMERG: different cells ({cells.loc['feni'].cell_lat:.2f}, {cells.loc['feni'].cell_lon:.2f} vs "
        f"{cells.loc['noakhali'].cell_lat:.2f}, {cells.loc['noakhali'].cell_lon:.2f}); identical rain on "
        f"{same_days * 100:.0f}% of days (mostly dry days on both), daily r = {f_i.corr(n_i):.2f}.")
    add(f"- IMERG mean annual total {ann_f.index.min()}-{ann_f.index.max()}: Feni {ann_f.mean():.0f} mm, "
        f"Noakhali {ann_n.mean():.0f} mm (Noakhali - Feni {ann_n.mean() - ann_f.mean():+.0f} mm; "
        f"Noakhali wetter in {(ann_n > ann_f).sum()} of {len(ann_f)} years; Wilcoxon signed-rank "
        f"{fmt_p(w_ann.pvalue)}).")
    add(f"- IMERG mean Jun-Sep total {jj_f.index.min()}-{jj_f.index.max()}: Feni {jj_f.mean():.0f} mm, "
        f"Noakhali {jj_n.mean():.0f} mm (Noakhali - Feni {jj_n.mean() - jj_f.mean():+.0f} mm; "
        f"Noakhali wetter in {(jj_n > jj_f).sum()} of {len(jj_f)} years; Wilcoxon {fmt_p(w_jj.pvalue)}).")
    differ = w_ann.pvalue < ALPHA or w_jj.pvalue < ALPHA
    add("- **" + ("Yes, but only a little: with IMERG the two districts have their own rain records, "
                  f"and Noakhali is consistently wetter, by about {(ann_n.mean() / ann_f.mean() - 1) * 100:.0f}% "
                  f"a year ({(jj_n.mean() / jj_f.mean() - 1) * 100:.0f}% in Jun-Sep). The neighbouring "
                  "0.1 degree cells share their monthly gauge adjustment, so treat this as a small "
                  "difference, not a headline contrast." if differ else
                  "Their rain records are now separate, but the totals do not differ significantly; "
                  "do not claim a Feni-Noakhali rain contrast.") + "** Temperature, humidity, wind and "
        "solar radiation still come from the one shared POWER cell, so any contrast is in rain only.")
    add("")

    # --- Yearly tables --------------------------------------------------------------
    for label, table, note in (("Annual totals (mm)", annual, "complete years"),
                               ("Jun-Sep totals (mm)", jjas, "complete seasons")):
        add(f"## {label}, POWER vs IMERG ({note})")
        add("")
        add("| Year | " + " | ".join(f"{n.title()} POWER | {n.title()} IMERG" for n in DISTRICTS) + " |")
        add("|---|" + "---|" * (2 * len(DISTRICTS)))
        for year in table["feni"]["IMERG"].index:
            row = []
            for name in DISTRICTS:
                row += [f"{table[name]['POWER'].get(year, np.nan):.0f}",
                        f"{table[name]['IMERG'].get(year, np.nan):.0f}"]
            add(f"| {year} | " + " | ".join(row) + " |")
        add("")

    add_station_normals(add, annual, jjas)
    add("## Sources")
    add("")
    for key in ("imerg", "power"):
        add(f"- {RAIN_CITATIONS[key]['dataset']}: {RAIN_CITATIONS[key]['url']}")
    add("- NASA Giovanni time-series API: https://api.giovanni.earthdata.nasa.gov/")
    add("- Pettitt, A. N. (1979). A non-parametric approach to the change-point problem. "
        "*Applied Statistics* 28(2), 126-135. https://doi.org/10.2307/2346729")
    add("- Bangladesh Meteorological Department, Average Normal Rainfall in mm: "
        "https://server8.bmd.gov.bd/file/2016/08/17/pdf/53.pdf")
    add("- Wilcoxon signed-rank test: `scipy.stats.wilcoxon`, "
        "https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.wilcoxon.html")

    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {OUT_PATH}")
    print("IMERG step change:", imerg_breaks or "none")
    print("POWER step change:", power_breaks or "none")


def add_station_normals(add, annual, jjas):
    """BMD station normals (data/reference/bmd_normal_rainfall.csv) vs both gridded records."""
    ref = pd.read_csv(BMD_PATH)
    ref[["station", "item_name"]] = ref["item"].str.split(".", n=1, expand=True)
    add("## BMD station normals")
    add("")
    add(f"From `data/reference/bmd_normal_rainfall.csv`: {ref.source_title.iloc[0]}, "
        f"{ref.source_url.iloc[0]}. The table does **not** state its averaging period, so this is a "
        "rough level check, not a like-for-like comparison. A station is one rain gauge; POWER and "
        "IMERG are cell averages. There is no BMD station for Brahmanbaria in the table.")
    add("")
    add("| District (BMD station) | BMD normal, annual (mm) | POWER annual 2001-2014 / 2016-2024 (mm) "
        "| IMERG annual 2001-2024 (mm) | BMD normal, Jun-Sep (mm) | POWER Jun-Sep 2001-2014 / 2016-2025 (mm) "
        "| IMERG Jun-Sep 2001-2025 (mm) |")
    add("|---|---|---|---|---|---|---|")
    for name, station in BMD_STATIONS.items():
        months = ref[ref.station == station].set_index("item_name")["value"]
        bmd_year = months.sum()
        bmd_jjas = months[[f"normal_rain_{m}" for m in ("jun", "jul", "aug", "sep")]].sum()
        pa, ia = annual[name]["POWER"], annual[name]["IMERG"]
        pj, ij = jjas[name]["POWER"], jjas[name]["IMERG"]
        add(f"| {name.title()} ({station.replace('_', ' ').title()}) | {bmd_year:.0f} "
            f"| {pa.loc[2001:2014].mean():.0f} / {pa.loc[2016:2024].mean():.0f} | {ia.mean():.0f} "
            f"| {bmd_jjas:.0f} | {pj.loc[2001:2014].mean():.0f} / {pj.loc[2016:2025].mean():.0f} "
            f"| {ij.mean():.0f} |")
    add("")
    add("Neither gridded record matches the gauges exactly. POWER sits below the station normals "
        "before 2015 and above them after, which is the step change again. IMERG is steady and "
        "within about 20% of the station normals, lower than the gauges at the wettest stations "
        "(Feni, Maijdi Court, Sylhet) and a little higher at Comilla.")
    add("")


BMD_PATH = os.path.join(ROOT, "data", "reference", "bmd_normal_rainfall.csv")
BMD_STATIONS = {"cumilla": "comilla", "feni": "feni", "noakhali": "maijdi_court", "sylhet": "sylhet"}

if __name__ == "__main__":
    main()
