"""
src/agents/guard.py

The provenance gate for Layer 3 (the agent's narrated answer). Before any
text generated by the model reaches a user, guard() checks every number in
it against the tool results the model actually received this turn. A number
is allowed only if it appears somewhere inside a tool result that itself
carries a citation (both a "dataset" and a "url"). Anything else -- a
number the model invented, rounded on its own, or pulled from an uncited
tool result -- is blocked.

No AI calls happen here. This is plain Python so it can't be talked out of
doing its job.
"""

import re

_BANGLA_DIGITS = "০১২৩৪৫৬৭৮৯"
_BANGLA_TO_ASCII = str.maketrans(_BANGLA_DIGITS, "0123456789")

# One or more ASCII/Bangla digits, optional comma grouping, optional decimal
# part, optional trailing percent sign.
_NUMBER_RE = re.compile(
    r"[0-9০-৯](?:[0-9০-৯,]*[0-9০-৯])?"
    r"(?:\.[0-9০-৯]+)?%?"
)

# Absolute and relative tolerance for "the model rounded a cited number".
_ABS_TOLERANCE = 0.01
_REL_TOLERANCE = 0.005


def _to_float(digits):
    ascii_digits = digits.translate(_BANGLA_TO_ASCII).replace(",", "")
    return float(ascii_digits)


def find_numbers(text):
    """Returns a list of {"raw": str, "value": float} for every number in
    text, English or Bangla digits, with comma grouping and a trailing %
    both handled. "value" ignores a trailing % (58% -> 58.0), since guard()
    compares against tool-result magnitudes, not fractions."""
    numbers = []
    for match in _NUMBER_RE.finditer(text):
        raw = match.group(0)
        core = raw[:-1] if raw.endswith("%") else raw
        try:
            value = _to_float(core)
        except ValueError:
            continue
        numbers.append({"raw": raw, "value": value})
    return numbers


def _is_cited(result):
    """A tool result is citable if it (or any entry in a "sources" list)
    carries both a "dataset" and a "url"."""
    if not isinstance(result, dict):
        return False
    source = result.get("source")
    if isinstance(source, dict) and "dataset" in source and "url" in source:
        return True
    for source in result.get("sources", []) or []:
        if isinstance(source, dict) and "dataset" in source and "url" in source:
            return True
    return False


def _collect_numbers(value, out):
    if isinstance(value, bool):
        return
    if isinstance(value, (int, float)):
        out.append(float(value))
    elif isinstance(value, dict):
        for v in value.values():
            _collect_numbers(v, out)
    elif isinstance(value, (list, tuple)):
        for v in value:
            _collect_numbers(v, out)


def _allowed_numbers(tool_results):
    if isinstance(tool_results, dict):
        results = list(tool_results.values())
    elif isinstance(tool_results, (list, tuple)):
        results = list(tool_results)
    else:
        results = [tool_results]

    allowed = []
    for result in results:
        if _is_cited(result):
            _collect_numbers(result, allowed)
    return allowed


def _matches(value, allowed_numbers):
    for allowed in allowed_numbers:
        tolerance = max(_ABS_TOLERANCE, abs(allowed) * _REL_TOLERANCE)
        if abs(value - allowed) <= tolerance:
            return True
    return False


def guard(text, tool_results):
    """Checks every number in `text` against `tool_results` (a list, or a
    dict keyed by tool name, of the raw dicts the tools returned this
    turn). Returns {"passed", "blocked_numbers", "checked"}. A number
    passes only if a cited tool result (dataset + url) contains a matching
    value, within rounding tolerance."""
    allowed_numbers = _allowed_numbers(tool_results)
    found = find_numbers(text)

    blocked_numbers = [
        number["raw"] for number in found
        if not _matches(number["value"], allowed_numbers)
    ]

    return {
        "passed": len(blocked_numbers) == 0,
        "blocked_numbers": blocked_numbers,
        "checked": len(found),
    }
